### ISSUE TITLE
hiding external links when using Kiwix plug

### ISSUE THREAD

**Issue by Popolechien** [kiwix/plug#1]
When reading ZIM files from a plug, clicking on them leads back to home page or error message. Lots of pages on Wiktionary and wikivoyage have ext. links, it really makes for a bad UX.

Same thing for Openstreetmap in Wikivoyage - box does not show map but frame with error message (unsightly)
(https://cloud.githubusercontent.com/assets/21675885/18169533/cd6942ce-705a-11e6-9e55-a65d89d04c50.png)

Possible solution: change external links to nolinks, eg. similar to what there is for non-article space internal links 
![screenshot_2016-09-01-15-42-16]

**Comment by kelson42** [comment]
Like on Wikipedia, external links are marked with a dedicated icon... Why do you click on it?
The openstreetmap is an other bug... but really not easy to fix.
