### ISSUE TITLE
Use without the WiFi hotspot function

### ISSUE THREAD

**Issue by ghost** [kiwix/plug#10]
I'm trying to use kiwix-plug on a Raspberry Pi that's already providing other services and is plugged into a switch. So basically I want a system just like kiwix-plug but without the WiFi hotspot thing.
Can you give me some pointers on how to do this?
I'm having a hard time compiling kiwix-serve because I'm getting some cryptic compilation errors. I can provide those on demand.
Thanks!

**Comment by kelson42** [comment]
@yassinei If you only want to have an HTTP daemon serving ZIM files, kiwix-serve is what you are aiming for. Try to download one of the last nightly for your OS here https://download.kiwix.org/nightly/.

**Comment by ghost** [comment]
I didn't know those existed. Very convenient, thank you.
